version: '3'

services:
  db:
    image: mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=mysql1234
      - MYSQL_DATABASE=descomplica_agenda
      - MYSQL_USER=mysql_user
      - MYSQL_PASSWORD:mysql1234